Last login: Wed Dec 30 20:37:25 on console
[oh-my-zsh] Insecure completion-dependent directories detected:
drwxrwxr-x  3 shindo  admin   96 Dec 19 13:23 /usr/local/share/zsh
drwxrwxr-x  4 shindo  admin  128 Dec 19 13:30 /usr/local/share/zsh/site-functions

[oh-my-zsh] For safety, we will not load completions from these directories until
[oh-my-zsh] you fix their permissions and ownership and restart zsh.
[oh-my-zsh] See the above list for directories with group or other writability.

[oh-my-zsh] To fix your permissions you can do so by disabling
[oh-my-zsh] the write permission of "group" and "others" and making sure that the
[oh-my-zsh] owner of these directories is either root or your current user.
[oh-my-zsh] The following command may help:
[oh-my-zsh]     compaudit | xargs chmod g-w,o-w

[oh-my-zsh] If the above didn't help or you want to skip the verification of
[oh-my-zsh] insecure directories you can set the variable ZSH_DISABLE_COMPFIX to
[oh-my-zsh] "true" before oh-my-zsh is sourced in your zshrc file.

 shindo@Shindos-iMac  ~  cd ~/.config/nvim
 shindo@Shindos-iMac  ~/.config/nvim   master ±  git status
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   init.vim

no changes added to commit (use "git add" and/or "git commit -a")
 shindo@Shindos-iMac  ~/.config/nvim   master ±  ll
total 72
-rw-r--r--  1 shindo  staff   212B Dec 19 17:12 coc-settings.json
-rw-r--r--  1 shindo  staff    17K Dec 30 14:38 init.vim
-rw-r--r--@ 1 shindo  staff   8.4K Dec 29 09:35 used.vim
 shindo@Shindos-iMac  ~/.config/nvim   master ±  git add .
 shindo@Shindos-iMac  ~/.config/nvim   master ✚  git commit -m
error: switch `m' requires a value
 ✘ shindo@Shindos-iMac  ~/.config/nvim   master ✚  git commit -m "final init.vim"
[master b50c09c] final init.vim
 1 file changed, 14 insertions(+), 3 deletions(-)
 shindo@Shindos-iMac  ~/.config/nvim   master  git remote origin https://github.com/sonlam806/dotfiles.git
error: Unknown subcommand: origin
usage: git remote [-v | --verbose]
   or: git remote add [-t <branch>] [-m <master>] [-f] [--tags | --no-tags] [--mirror=<fetch|push>] <name> <url>
   or: git remote rename <old> <new>
   or: git remote remove <name>
   or: git remote set-head <name> (-a | --auto | -d | --delete | <branch>)
   or: git remote [-v | --verbose] show [-n] <name>
   or: git remote prune [-n | --dry-run] <name>
 #    .tmux.conf
  1 set -g default-terminal "xterm-256color"
  2 #set -ga terminal-overrides ",*256col*:Tc"
  3 set -ga terminal-overrides ",xterm-256color:Tc"
  4 # action key
  5 unbind C-b
  6 set-option -g prefix C-q
  7 set-option -g repeat-time 0
  8
  9 #### Key bindings
 10
 11 set-window-option -g mode-keys vi
 12
 13 #bind t send-key C-t
 14 # Reload settings
 15 bind r source-file ~/.tmux.conf \; display "Reloaded!"
 16 # Open current directory
 17 bind o run-shell "open #{pane_current_path}"
 18 bind -r e kill-pane -a
 19
 20 # split panes using | and -
 21 bind | split-window -h
 22 bind - split-window -v
 23 unbind '"'
 24 unbind %
 25
 26 # vim-like pane switching
 27 bind -r k select-pane -U
 28 bind -r j select-pane -D
 29 bind -r h select-pane -L
 30 bind -r l select-pane -R
 31
 32 # Moving window
 33 bind-key -n C-S-Left swap-window -t -1 \; previous-window
 34 bind-key -n C-S-Right swap-window -t +1 \; next-window
 35
 36 # Resizing pane
 37 bind -r C-k resize-pane -U 5
 38 bind -r C-j resize-pane -D 5
 39 bind -r C-h resize-pane -L 5
 40 bind -r C-l resize-pane -R 5
 41
 42 #### basic settings
 43
 44 set-option -g status-justify "left"
 NORMAL  .tmux.conf                                                                                                                        tmux  utf-8[unix]  8% ☰ 8/95 ㏑:1  ☲ [27]trailing
".tmux.conf" 95L, 2457C written
